# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superMarket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
