# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-10 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superMarket', '0002_auto_20170310_0738'),
    ]

    operations = [
        migrations.CreateModel(
            name='cmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='csdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='gmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='gsmdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='scdb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sex', models.CharField(blank=True, db_column='sex', max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(blank=True, db_column='sex', max_length=3),
        ),
    ]
