# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom',
            fields=[
                ('customId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('openid', models.CharField(max_length=64, null=True)),
                ('username', models.CharField(max_length=64, null=True)),
                ('password', models.CharField(max_length=64, null=True)),
                ('tel', models.CharField(max_length=32, null=True)),
                ('remark', models.TextField(null=True)),
                ('typess', models.CharField(max_length=16, null=True)),
                ('status', models.CharField(max_length=16, null=True)),
            ],
            options={
                'db_table': 'customManager',
            },
        ),
        migrations.CreateModel(
            name='CustomOrder',
            fields=[
                ('customOrderId', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('orderId', models.CharField(max_length=64, null=True)),
                ('customId', models.CharField(max_length=64, null=True)),
                ('amount', models.CharField(max_length=64, null=True)),
                ('payment', models.CharField(max_length=64, null=True)),
                ('description', models.CharField(max_length=64, null=True)),
                ('createTime', models.CharField(max_length=64, null=True)),
                ('shopId', models.CharField(max_length=64, null=True)),
                ('result', models.CharField(max_length=64, null=True)),
            ],
            options={
                'db_table': 'customOrder',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customOrderId', models.CharField(max_length=64, null=True)),
                ('skuCode', models.CharField(max_length=64, null=True)),
                ('customId', models.CharField(max_length=64, null=True)),
                ('skuCount', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'orderItem',
            },
        ),
        migrations.CreateModel(
            name='Verify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.CharField(max_length=20, null=True)),
                ('code', models.CharField(max_length=4, null=True)),
                ('time_code', models.CharField(max_length=64, null=True)),
                ('flag', models.CharField(default=b'0', max_length=1, null=True)),
            ],
        ),
    ]
