# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-11 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='typess',
            new_name='types',
        ),
    ]
