# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0002_auto_20171011_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom',
            name='status',
            field=models.CharField(default=b'0', max_length=16),
        ),
        migrations.AlterField(
            model_name='custom',
            name='types',
            field=models.CharField(default=b'0', max_length=16),
        ),
    ]
