# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-16 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weixin', '0003_auto_20171012_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='custom',
            name='isused',
            field=models.CharField(default=b'0', max_length=16),
        ),
    ]
